name: Publish Pipeline

on:
  push:
    branches: ["main", "develop"]

jobs:
  build-jar:
    uses: catalis-vc/cicd/.github/workflows/build-maven.yaml@main
    with:
      java-version: "21"
      skip-tests: false
      jar-path: "common-platform-reference-master-data-web/target/common-platform-reference-master-data.jar"
    secrets:
      PAT_GITHUB_PACKAGE: ${{ secrets.PAT_GITHUB_PACKAGE }}

  docker-publish:
    needs: [build-jar]
    uses: catalis-vc/cicd/.github/workflows/docker-publish.yaml@main
    with:
      dockerfile-path: "./Dockerfile"
      azure-registry-name: "catalis.azurecr.io"
      azure-registry-repository: "common-platform-reference-master-data"
      docker-image-tag: "latest"
    secrets:
      AZURE_ACR_USERNAME: ${{ secrets.AZURE_ACR_USERNAME }}
      AZURE_ACR_PASSWORD: ${{ secrets.AZURE_ACR_PASSWORD }}